name: 🐛 Bug Report
description: Something isn't working right? Tell us about it.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us polish the app! Please fill out the details below.
  - type: input
    id: device
    attributes:
      label: Device Model
      description: e.g., Pixel 7, Samsung S23 Ultra
      placeholder: Pixel 7 Pro
    validations:
      required: true
  - type: dropdown
    id: android_version
    attributes:
      label: Android Version
      options:
        - Android 14
        - Android 13
        - Android 12
        - Other (please specify in description)
    validations:
      required: true
  - type: dropdown
    id: affected_feature
    attributes:
      label: Affected Feature
      description: Which part of the Island is broken?
      options:
        - Notifications & Reply
        - Music Visualizer
        - Phone Calls
        - Privacy Indicators
        - Bluetooth/Battery
        - General UI/Animation
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: What happened? What did you expect to happen?
      placeholder: When I receive a WhatsApp message, the island expands but the reply button is missing...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we make this happen on our phones?
      placeholder: 1. Play music on Spotify. 2. Lock screen. 3. Tap the island...
    validations:
      required: false
